export enum FontStyleType {
  display_1_b = "display_1_b",
  display_1_sb = "display_1_sb",
  display_2_b = "display_2_b",
  display_2_sb = "display_2_sb",
  display_3_b = "display_3_b",
  display_3_sb = "display_3_sb",
  heading_1_b = "heading_1_b",
  heading_1_sb = "heading_1_sb",
  heading_1_m = "heading_1_m",
  heading_2_b = "heading_2_b",
  heading_2_sb = "heading_2_sb",
  heading_2_m = "heading_2_m",
  heading_3_b = "heading_3_b",
  heading_3_sb = "heading_3_sb",
  heading_3_m = "heading_3_m",
  title_1_b = "title_1_b",
  title_1_sb = "title_1_sb",
  title_1_m = "title_1_m",
  title_2_b = "title_2_b",
  title_2_sb = "title_2_sb",
  title_2_m = "title_2_m",
  title_3_b = "title_3_b",
  title_3_sb = "title_3_sb",
  title_3_m = "title_3_m",
  body_1_b = "body_1_b",
  body_1_sb = "body_1_sb",
  body_1_m = "body_1_m",
  body_2_b = "body_2_b",
  body_2_sb = "body_2_sb",
  body_2_m = "body_2_m",
  body_3_b = "body_3_b",
  body_3_sb = "body_3_sb",
  body_3_m = "body_3_m",
  caption_1_sb = "caption_1_sb",
  caption_1_m = "caption_1_m",
  caption_2_sb = "caption_2_sb",
  caption_2_m = "caption_2_m",
}

export const FontStyle = {
  display_1_b: {
    fontSize: "64px",
    fontWeight: "700",
    lineHeight: "82px",
    letterSpacing: "-0.64px",
  },
  display_1_sb: {
    fontSize: "64px",
    fontWeight: "600",
    lineHeight: "82px",
    letterSpacing: "-0.64px",
  },
  display_2_b: {
    fontSize: "56px",
    fontWeight: "700",
    lineHeight: "72px",
    letterSpacing: "-0.56px",
  },
  display_2_sb: {
    fontSize: "56px",
    fontWeight: "600",
    lineHeight: "72px",
    letterSpacing: "-0.56px",
  },
  display_3_b: {
    fontSize: "48px",
    fontWeight: "700",
    lineHeight: "60px",
    letterSpacing: "-0.48px",
  },
  display_3_sb: {
    fontSize: "48px",
    fontWeight: "600",
    lineHeight: "60px",
    letterSpacing: "-0.48px",
  },
  heading_1_b: {
    fontSize: "40px",
    fontWeight: "700",
    lineHeight: "52px",
  },
  heading_1_sb: {
    fontSize: "40px",
    fontWeight: "600",
    lineHeight: "52px",
  },
  heading_1_m: {
    fontSize: "40px",
    fontWeight: "500",
    lineHeight: "52px",
  },
  heading_2_b: {
    fontSize: "32px",
    fontWeight: "700",
    lineHeight: "40px",
  },
  heading_2_sb: {
    fontSize: "32px",
    fontWeight: "600",
    lineHeight: "40px",
  },
  heading_2_m: {
    fontSize: "32px",
    fontWeight: "500",
    lineHeight: "40px",
  },
  heading_3_b: {
    fontSize: "28px",
    fontWeight: "700",
    lineHeight: "38px",
  },
  heading_3_sb: {
    fontSize: "28px",
    fontWeight: "600",
    lineHeight: "38px",
  },
  heading_3_m: {
    fontSize: "28px",
    fontWeight: "500",
    lineHeight: "38px",
  },
  title_1_b: {
    fontSize: "24px",
    fontWeight: "700",
    lineHeight: "32px",
  },
  title_1_sb: {
    fontSize: "24px",
    fontWeight: "600",
    lineHeight: "32px",
  },
  title_1_m: {
    fontSize: "24px",
    fontWeight: "500",
    lineHeight: "32px",
  },
  title_2_b: {
    fontSize: "20px",
    fontWeight: "700",
    lineHeight: "30px",
  },
  title_2_sb: {
    fontSize: "20px",
    fontWeight: "600",
    lineHeight: "30px",
  },
  title_2_m: {
    fontSize: "20px",
    fontWeight: "500",
    lineHeight: "30px",
  },
  title_3_b: {
    fontSize: "18px",
    fontWeight: "700",
    lineHeight: "28px",
  },
  title_3_sb: {
    fontSize: "18px",
    fontWeight: "600",
    lineHeight: "28px",
  },
  title_3_m: {
    fontSize: "18px",
    fontWeight: "500",
    lineHeight: "28px",
  },
  body_1_b: {
    fontSize: "16px",
    fontWeight: "700",
    lineHeight: "24px",
  },
  body_1_sb: {
    fontSize: "16px",
    fontWeight: "600",
    lineHeight: "24px",
  },
  body_1_m: {
    fontSize: "16px",
    fontWeight: "500",
    lineHeight: "24px",
  },
  body_2_b: {
    fontSize: "14px",
    fontWeight: "700",
    lineHeight: "20px",
  },
  body_2_sb: {
    fontSize: "14px",
    fontWeight: "600",
    lineHeight: "20px",
  },
  body_2_m: {
    fontSize: "14px",
    fontWeight: "500",
    lineHeight: "20px",
  },
  body_3_b: {
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "18px",
  },
  body_3_sb: {
    fontSize: "13px",
    fontWeight: "600",
    lineHeight: "18px",
  },
  body_3_m: {
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: "18px",
  },

  caption_1_sb: {
    fontSize: "12px",
    fontWeight: "600",
    lineHeight: "16px",
  },
  caption_1_m: {
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: "16px",
  },

  caption_2_sb: {
    fontSize: "11px",
    fontWeight: "600",
    lineHeight: "14px",
  },
  caption_2_m: {
    fontSize: "11px",
    fontWeight: "500",
    lineHeight: "14px",
  },
};
