export enum FontStyleType {
  DISPLAY_1_B = 'DISPLAY_1_B',
  DISPLAY_1_SB = 'DISPLAY_1_SB',
  DISPLAY_2_B = 'DISPLAY_2_B',
  DISPLAY_2_SB = 'DISPLAY_2_SB',
  DISPLAY_3_B = 'DISPLAY_3_B',
  DISPLAY_3_SB = 'DISPLAY_3_SB',
  HEADING_1_B = 'HEADING_1_B',
  HEADING_1_SB = 'HEADING_1_SB',
  HEADING_1_M = 'HEADING_1_M',
  HEADING_2_B = 'HEADING_2_B',
  HEADING_2_SB = 'HEADING_2_SB',
  HEADING_2_M = 'HEADING_2_M',
  HEADING_3_B = 'HEADING_3_B',
  HEADING_3_SB = 'HEADING_3_SB',
  HEADING_3_M = 'HEADING_3_M',
  TITLE_1_B = 'TITLE_1_B',
  TITLE_1_SB = 'TITLE_1_SB',
  TITLE_1_M = 'TITLE_1_M',
  TITLE_2_B = 'TITLE_2_B',
  TITLE_2_SB = 'TITLE_2_SB',
  TITLE_2_M = 'TITLE_2_M',
  TITLE_3_B = 'TITLE_3_B',
  TITLE_3_SB = 'TITLE_3_SB',
  TITLE_3_M = 'TITLE_3_M',
  BODY_1_B = 'BODY_1_B',
  BODY_1_SB = 'BODY_1_SB',
  BODY_1_M = 'BODY_1_M',
  BODY_2_B = 'BODY_2_B',
  BODY_2_SB = 'BODY_2_SB',
  BODY_2_M = 'BODY_2_M',
  BODY_3_B = 'BODY_3_B',
  BODY_3_SB = 'BODY_3_SB',
  BODY_3_M = 'BODY_3_M',
  CAPTION_1_SB = 'CAPTION_1_SB',
  CAPTION_1_M = 'CAPTION_1_M',
  CAPTION_2_SB = 'CAPTION_2_SB',
  CAPTION_2_M = 'CAPTION_2_M',
}

export const FontStyle = {
  DISPLAY_1_B: {
    fontSize: '64px',
    fontWeight: '700',
    lineHeight: '82px',
    letterSpacing: '-0.64px',
  },
  DISPLAY_1_SB: {
    fontSize: '64px',
    fontWeight: '600',
    lineHeight: '82px',
    letterSpacing: '-0.64px',
  },
  DISPLAY_2_B: {
    fontSize: '56px',
    fontWeight: '700',
    lineHeight: '72px',
    letterSpacing: '-0.56px',
  },
  DISPLAY_2_SB: {
    fontSize: '56px',
    fontWeight: '600',
    lineHeight: '72px',
    letterSpacing: '-0.56px',
  },
  DISPLAY_3_B: {
    fontSize: '48px',
    fontWeight: '700',
    lineHeight: '60px',
    letterSpacing: '-0.48px',
  },
  DISPLAY_3_SB: {
    fontSize: '48px',
    fontWeight: '600',
    lineHeight: '60px',
  },
  HEADING_1_B: {
    fontSize: '40px',
    fontWeight: '700',
    lineHeight: '52px',
  },
  HEADING_1_SB: {
    fontSize: '40px',
    fontWeight: '600',
    lineHeight: '52px',
  },
  HEADING_1_M: {
    fontSize: '40px',
    fontWeight: '500',
    lineHeight: '52px',
  },
  HEADING_2_B: {
    fontSize: '32px',
    fontWeight: '700',
    lineHeight: '40px',
  },
  HEADING_2_SB: {
    fontSize: '32px',
    fontWeight: '600',
    lineHeight: '40px',
  },
  HEADING_2_M: {
    fontSize: '32px',
    fontWeight: '500',
    lineHeight: '40px',
  },
  HEADING_3_B: {
    fontSize: '28px',
    fontWeight: '700',
    lineHeight: '38px',
  },
  HEADING_3_SB: {
    fontSize: '28px',
    fontWeight: '600',
    lineHeight: '38px',
  },
  HEADING_3_M: {
    fontSize: '28px',
    fontWeight: '500',
    lineHeight: '38px',
  },
  TITLE_1_B: {
    fontSize: '24px',
    fontWeight: '700',
    lineHeight: '32px',
  },
  TITLE_1_SB: {
    fontSize: '24px',
    fontWeight: '600',
    lineHeight: '32px',
  },
  TITLE_1_M: {
    fontSize: '24px',
    fontWeight: '500',
    lineHeight: '32px',
  },
  TITLE_2_B: {
    fontSize: '20px',
    fontWeight: '700',
    lineHeight: '28px',
  },
  TITLE_2_SB: {
    fontSize: '20px',
    fontWeight: '600',
    lineHeight: '28px',
  },
  TITLE_2_M: {
    fontSize: '20px',
    fontWeight: '500',
    lineHeight: '28px',
  },
  TITLE_3_B: {
    fontSize: '18px',
    fontWeight: '700',
    lineHeight: '26px',
  },
  TITLE_3_SB: {
    fontSize: '18px',
    fontWeight: '600',
    lineHeight: '26px',
  },
  TITLE_3_M: {
    fontSize: '18px',
    fontWeight: '500',
    lineHeight: '26px',
  },
  BODY_1_B: {
    fontSize: '16px',
    fontWeight: '700',
    lineHeight: '24px',
  },
  BODY_1_SB: {
    fontSize: '16px',
    fontWeight: '600',
    lineHeight: '24px',
  },
  BODY_1_M: {
    fontSize: '16px',
    fontWeight: '500',
    lineHeight: '24px',
  },
  BODY_2_B: {
    fontSize: '14px',
    fontWeight: '700',
    lineHeight: '22px',
  },
  BODY_2_SB: {
    fontSize: '14px',
    fontWeight: '600',
    lineHeight: '22px',
  },
  BODY_2_M: {
    fontSize: '14px',
    fontWeight: '500',
    lineHeight: '22px',
  },
  BODY_3_B: {
    fontSize: '13px',
    fontWeight: '700',
    lineHeight: '18px',
  },
  BODY_3_SB: {
    fontSize: '13px',
    fontWeight: '600',
    lineHeight: '18px',
  },
  BODY_3_M: {
    fontSize: '13px',
    fontWeight: '500',
    lineHeight: '18px',
  },
  CAPTION_1_SB: {
    fontSize: '12px',
    fontWeight: '600',
    lineHeight: '16px',
  },
  CAPTION_1_M: {
    fontSize: '12px',
    fontWeight: '500',
    lineHeight: '16px',
  },

  CAPTION_2_SB: {
    fontSize: '11px',
    fontWeight: '600',
    lineHeight: '14px',
  },
  CAPTION_2_M: {
    fontSize: '11px',
    fontWeight: '500',
    lineHeight: '14px',
  },
};
