export const MILLISECONDS_PER_SECONDS = 1000;
export const MILLISECONDS_PER_MINUTE = 60 * MILLISECONDS_PER_SECONDS;
export const MILLISECONDS_PER_HOUR = 60 * MILLISECONDS_PER_MINUTE;
export const MILLISECONDS_PER_DAY = 24 * MILLISECONDS_PER_HOUR;
