import ColorType from '@constant/styles/color/ColorType';

export enum TextElementType {
  h1 = 'h1',
  h2 = 'h2',
  h3 = 'h3',
  h4 = 'h4',
  h5 = 'h5',
  h6 = 'h6',
  div = 'div',
  span = 'span',
  em = 'em',
  strong = 'strong',
  p = 'p',
}

export enum TextColorType {
  strong = 'strong',
  default = 'default',
  subtle = 'subtle',
  subtlest = 'subtlest',
  inverse = 'inverse',
  disabled = 'disabled',
  brand = 'brand',
  success = 'success',
  danger = 'danger',
  warning = 'warning',
  information = 'information',
  accent_green_default = 'accent_green_default',
  accent_green_subtle = 'accent_green_subtle',
  accent_green_strong = 'accent_green_strong',
  accent_springgreen_default = 'accent_springgreen_default',
  accent_springgreen_subtle = 'accent_springgreen_subtle',
  accent_springgreen_strong = 'accent_springgreen_strong',
  accent_olivegreen_default = 'accent_olivegreen_default',
  accent_olivegreen_subtle = 'accent_olivegreen_subtle',
  accent_olivegreen_strong = 'accent_olivegreen_strong',
  accent_yellow_default = 'accent_yellow_default',
  accent_yellow_subtle = 'accent_yellow_subtle',
  accent_yellow_strong = 'accent_yellow_strong',
  accent_gold_default = 'accent_gold_default',
  accent_gold_subtle = 'accent_gold_subtle',
  accent_gold_strong = 'accent_gold_strong',
  accent_orange_default = 'accent_orange_default',
  accent_orange_subtle = 'accent_orange_subtle',
  accent_orange_strong = 'accent_orange_strong',
  accent_red_default = 'accent_red_default',
  accent_red_subtle = 'accent_red_subtle',
  accent_red_strong = 'accent_red_strong',
  accent_pink_default = 'accent_pink_default',
  accent_pink_subtle = 'accent_pink_subtle',
  accent_pink_strong = 'accent_pink_strong',
  accent_purple_default = 'accent_purple_default',
  accent_purple_subtle = 'accent_purple_subtle',
  accent_purple_strong = 'accent_purple_strong',
  accent_violet_default = 'accent_violet_default',
  accent_violet_subtle = 'accent_violet_subtle',
  accent_violet_strong = 'accent_violet_strong',
  accent_cobaltblue_default = 'accent_cobaltblue_default',
  accent_cobaltblue_subtle = 'accent_cobaltblue_subtle',
  accent_cobaltblue_strong = 'accent_cobaltblue_strong',
  accent_skyblue_default = 'accent_skyblue_default',
  accent_skyblue_subtle = 'accent_skyblue_subtle',
  accent_skyblue_strong = 'accent_skyblue_strong',
  accent_cyan_default = 'accent_cyan_default',
  accent_cyan_subtle = 'accent_cyan_subtle',
  accent_cyan_strong = 'accent_cyan_strong',
  accent_teal_default = 'accent_teal_default',
  accent_teal_subtle = 'accent_teal_subtle',
  accent_teal_strong = 'accent_teal_strong',
}

export const TextColor: Record<TextColorType, ColorType> = {
  strong: ColorType.C_GRAY_800,
  default: ColorType.C_GRAY_700,
  subtle: ColorType.C_GRAY_500,
  subtlest: ColorType.C_GRAY_400,
  inverse: ColorType.C_GRAY_WHITE,
  disabled: ColorType.C_GRAY_300,
  brand: ColorType.C_GREEN_600,
  success: ColorType.C_GREEN_600,
  danger: ColorType.C_RED_600,
  warning: ColorType.C_YELLOW_600,
  information: ColorType.C_SKYBLUE_600,
  accent_green_default: ColorType.C_GREEN_600,
  accent_green_subtle: ColorType.C_GREEN_400,
  accent_green_strong: ColorType.C_GREEN_800,
  accent_springgreen_default: ColorType.C_SPRINGGREEN_600,
  accent_springgreen_subtle: ColorType.C_SPRINGGREEN_400,
  accent_springgreen_strong: ColorType.C_SPRINGGREEN_800,
  accent_olivegreen_default: ColorType.C_OLIVEGREEN_600,
  accent_olivegreen_subtle: ColorType.C_OLIVEGREEN_400,
  accent_olivegreen_strong: ColorType.C_OLIVEGREEN_800,
  accent_yellow_default: ColorType.C_YELLOW_600,
  accent_yellow_subtle: ColorType.C_YELLOW_400,
  accent_yellow_strong: ColorType.C_YELLOW_800,
  accent_gold_default: ColorType.C_GOLD_600,
  accent_gold_subtle: ColorType.C_GOLD_400,
  accent_gold_strong: ColorType.C_GOLD_800,
  accent_orange_default: ColorType.C_ORANGE_600,
  accent_orange_subtle: ColorType.C_ORANGE_400,
  accent_orange_strong: ColorType.C_ORANGE_800,
  accent_red_default: ColorType.C_RED_600,
  accent_red_subtle: ColorType.C_RED_400,
  accent_red_strong: ColorType.C_RED_800,
  accent_pink_default: ColorType.C_PINK_600,
  accent_pink_subtle: ColorType.C_PINK_400,
  accent_pink_strong: ColorType.C_PINK_800,
  accent_purple_default: ColorType.C_PURPLE_600,
  accent_purple_subtle: ColorType.C_PURPLE_400,
  accent_purple_strong: ColorType.C_PURPLE_800,
  accent_violet_default: ColorType.C_VIOLET_600,
  accent_violet_subtle: ColorType.C_VIOLET_400,
  accent_violet_strong: ColorType.C_VIOLET_800,
  accent_cobaltblue_default: ColorType.C_COBALTBLUE_600,
  accent_cobaltblue_subtle: ColorType.C_COBALTBLUE_400,
  accent_cobaltblue_strong: ColorType.C_COBALTBLUE_800,
  accent_skyblue_default: ColorType.C_SKYBLUE_600,
  accent_skyblue_subtle: ColorType.C_SKYBLUE_400,
  accent_skyblue_strong: ColorType.C_SKYBLUE_800,
  accent_cyan_default: ColorType.C_CYAN_600,
  accent_cyan_subtle: ColorType.C_CYAN_400,
  accent_cyan_strong: ColorType.C_CYAN_800,
  accent_teal_default: ColorType.C_TEAL_600,
  accent_teal_subtle: ColorType.C_TEAL_400,
  accent_teal_strong: ColorType.C_TEAL_800,
};
