import ColorType from '@constant/styles/color/ColorType';

export enum IconSizeType {
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
}

export enum IconColorType {
  strong = 'strong',
  default = 'default',
  subtle = 'subtle',
  subtlest = 'subtlest',
  inverse = 'inverse',
  disabled = 'disabled',
  primary = 'primary',
  success = 'success',
  danger = 'danger',
  warning = 'warning',
  information = 'information',
  accent_green = 'accent_green',
  accent_springgreen = 'accent_springgreen',
  accent_olivegreen = 'accent_olivegreen',
  accent_yellow = 'accent_yellow',
  accent_gold = 'accent_gold',
  accent_orange = 'accent_orange',
  accent_red = 'accent_red',
  accent_pink = 'accent_pink',
  accent_purple = 'accent_purple',
  accent_violet = 'accent_violet',
  accent_cobaltblue = 'accent_cobaltblue',
  accent_skyblue = 'accent_skyblue',
  accent_cyan = 'accent_cyan',
  accent_teal = 'accent_teal',
}

export const IconColors: Record<IconColorType, ColorType> = {
  strong: ColorType.C_GRAY_800,
  default: ColorType.C_GRAY_700,
  subtle: ColorType.C_GRAY_500,
  subtlest: ColorType.C_GRAY_400,
  inverse: ColorType.C_GRAY_WHITE,
  disabled: ColorType.C_GRAY_300,
  primary: ColorType.C_GREEN_600,
  success: ColorType.C_GREEN_600,
  danger: ColorType.C_RED_600,
  warning: ColorType.C_YELLOW_600,
  information: ColorType.C_SKYBLUE_600,
  accent_green: ColorType.C_GREEN_600,
  accent_springgreen: ColorType.C_SPRINGGREEN_600,
  accent_olivegreen: ColorType.C_OLIVEGREEN_600,
  accent_yellow: ColorType.C_YELLOW_600,
  accent_gold: ColorType.C_GOLD_600,
  accent_orange: ColorType.C_ORANGE_600,
  accent_red: ColorType.C_RED_600,
  accent_pink: ColorType.C_PINK_600,
  accent_purple: ColorType.C_PURPLE_600,
  accent_violet: ColorType.C_VIOLET_600,
  accent_cobaltblue: ColorType.C_COBALTBLUE_600,
  accent_skyblue: ColorType.C_SKYBLUE_600,
  accent_cyan: ColorType.C_CYAN_600,
  accent_teal: ColorType.C_TEAL_600,
};
