import Colors from "@constant/Colors/PaltetteType";

export enum IconSizeType {
  XS = "XS",
  S = "S",
  M = "M",
  L = "L",
  XL = "XL",
}

export enum IconColorType {
  strong = "strong",
  default = "default",
  subtle = "subtle",
  subtlest = "subtlest",
  inverse = "inverse",
  disabled = "disabled",
  primary = "primary",
  success = "success",
  danger = "danger",
  warning = "warning",
  information = "information",
  accent_green = "accent_green",
  accent_springgreen = "accent_springgreen",
  accent_olivegreen = "accent_olivegreen",
  accent_yellow = "accent_yellow",
  accent_gold = "accent_gold",
  accent_orange = "accent_orange",
  accent_red = "accent_red",
  accent_pink = "accent_pink",
  accent_purple = "accent_purple",
  accent_violet = "accent_violet",
  accent_cobaltblue = "accent_cobaltblue",
  accent_skyblue = "accent_skyblue",
  accent_cyan = "accent_cyan",
  accent_teal = "accent_teal",
}

export const IconColors: Record<IconColorType, Colors> = {
  strong: Colors.C_GRAY_800,
  default: Colors.C_GRAY_700,
  subtle: Colors.C_GRAY_500,
  subtlest: Colors.C_GRAY_400,
  inverse: Colors.C_GRAY_WHITE,
  disabled: Colors.C_GRAY_300,
  primary: Colors.C_GREEN_600,
  success: Colors.C_GREEN_600,
  danger: Colors.C_RED_600,
  warning: Colors.C_YELLOW_600,
  information: Colors.C_SKYBLUE_600,
  accent_green: Colors.C_GREEN_600,
  accent_springgreen: Colors.C_SPRINGGREEN_600,
  accent_olivegreen: Colors.C_OLIVEGREEN_600,
  accent_yellow: Colors.C_YELLOW_600,
  accent_gold: Colors.C_GOLD_600,
  accent_orange: Colors.C_ORANGE_600,
  accent_red: Colors.C_RED_600,
  accent_pink: Colors.C_PINK_600,
  accent_purple: Colors.C_PURPLE_600,
  accent_violet: Colors.C_VIOLET_600,
  accent_cobaltblue: Colors.C_COBALTBLUE_600,
  accent_skyblue: Colors.C_SKYBLUE_600,
  accent_cyan: Colors.C_CYAN_600,
  accent_teal: Colors.C_TEAL_600,
};
